#!/bin/bash

read -p 'Would you like to access the help page? [y/n]' help
read -p 'Which eyes? ' eyes
read -p 'Which arms? ' arms

echo ' ()_() '
echo " ($eyes.$eyes) "
echo "$arms(   )$arms"
echo ' () () '
