#!/bin/bash
echo ' ()_() '

case "$1" in
"^")
echo ' (^.^) '
;;
";")
echo ' (;-;) '
;;
"o")
echo ' (o.O) '
;;
".")
echo ' (._.) '
;;
"-")
echo ' (-.-) '
;;
">")
echo ' (>.<) '
;;
"OwO")
echo ' (OwO) '
;;
"*")
echo ' (*^*) '
;;
'blank')
echo ' (   ) '
;;
*)
echo ' (^.^) '
;;
esac

case "$2" in
"o")
echo 'o(   )o'
;;
"d")
echo 'd(   )b'
;;
"~")
echo '~(   )~'
;;
"V")
echo 'V(   )o'
;;
"<")
echo '<(   )>'
;;
*)
echo 'o(   )o'
;;
esac

echo ' () () '

if [[ "$1" == "help" ]]; then
echo "----------"
echo "Usage: custom [eyes] [arms]"
echo "Creates customizeable bunnies. Help page available when 'custom help' is typed in."
echo " "
echo "Eyes:"
echo "   ^       (^.^)"
echo "   ';'     (;-;)"
echo "   o       (o.O)"
echo "   .       (._.)"
echo "   -       (-.-)"
echo "   '>'     (>.<)"
echo "   OwO     (OwO)"
echo "   '*'     (*^*)"
echo "   blank   (   )"
echo "With no 'eyes' input, standard eyes (^.^)"
echo "Arms:"
echo "   o       o(   )o"
echo "   d       d(   )b"
echo "   '~'     ~(   )~"
echo "   V       V(   )o"
echo "   '<'     <(   )>"
echo "With no 'arms' input, standard arms o(   )o"
echo " "
echo "Examples:"
echo "   custom '*' d     Outputs bunny with eyes (*^*) and arms d(   )b"
echo "   custom           Outputs standard bunny with eyes (^.^) and arms o(   )o"
echo "   custom help      Outputs standard bunny and help page"
else
echo " "
fi
